Vagrant.require_version ">= 2.3.4"
Vagrant.configure("2") do |config|
  config.vm.box = "jborean93/WindowsServer2012R2"
  config.vm.box_version = "1.1.0"
  config.vm.define vm_name = '2012R2'
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
end
