Vagrant.require_version ">= 2.3.4"
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server"
  config.vm.box_version = "2102.0.2306"
  config.vm.define vm_name = 'windows'
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
end
