ENV["LC_ALL"] = "zh_TW.UTF-8"
Vagrant.require_version ">= 2.3.4"
Vagrant.configure(2) do |config|
  config.vm.box_version = "4.0.2"
  config.vm.box = "generic/debian10"
  config.vm.network "private_network", type: "dhcp" 
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision "shell", path: "./src/bootstrap.sh"

  (1..2).each do |i|
    config.vm.define "vm_0#{i}" do |node|
      config.vm.provider "virtualbox" do |node|
        node.name = "vm_0#{i}"  
			end
		end
	end
end