ENV["LC_ALL"] = "zh_TW.UTF-8"
Vagrant.require_version ">= 2.3.4"
Vagrant.configure(2) do |config|
   config.vm.box = "generic/debian10"
   config.vm.box_version = "4.0.2"
   config.vm.define vm_name = 'debian10'

   config.vm.provision "shell", privileged: false, inline: <<-SHELL
     sudo apt-get update
   SHELL

end
